#!/bin/sh
set -e
set -o pipefail

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

${SCRIPTPATH}/../tests/sdbus-c++-unit-tests 2>&1 | \
sed -r 's/^\[\s+OK\s+\] (.*) \([0-9]+\sms\)$/PASS: \1 /' | \
sed -r 's/^\[\s+FAILED\s+\] (.*) \([0-9]+\sms\)$/FAIL: \1 /' | \
awk '{if ($1 == "PASS:" || $1 == "FAIL:") {print $0}}'

${SCRIPTPATH}/../tests/sdbus-c++-integration-tests 2>&1 | \
sed -r 's/^\[\s+OK\s+\] (.*) \([0-9]+\sms\)$/PASS: \1 /' | \
sed -r 's/^\[\s+FAILED\s+\] (.*) \([0-9]+\sms\)$/FAIL: \1 /' | \
awk '{if ($1 == "PASS:" || $1 == "FAIL:") {print $0}}' 
