#!/bin/sh

#
# Minimal pg_config implementation as replacement for the native pg_config application
#

prefix=@SYSROOT@/usr

case "$1" in
  --includedir)
    echo "$prefix/include"
    ;;
  --pkgincludedir)
    echo "$prefix/include/postgresql"
    ;;
  --includedir-server)
    echo "$prefix/include/postgresql/server"
    ;;
  --libdir)
    echo "$prefix/lib"
    ;;
  --version)
    echo "PostgreSQL @POSTGRESQL_VERSION@"
    ;;
  --configure)
    echo "@POSTGRESQL_CONF_OPTIONS@"
    ;;
  --pgxs)
    echo "$prefix/lib/postgresql/pgxs/src/makefiles/pgxs.mk"
    ;;
  --cflags)
    echo "@TARGET_CFLAGS@"
    ;;
  --cc)
    echo "@TARGET_CC@"
    ;;
  --pkglibdir)
    echo "/usr/lib/postgresql"
    ;;
  --bindir)
    echo "/usr/bin"
    ;;
  --sharedir)
    echo "/usr/share/postgresql"
    ;;
  --localedir)
    echo "/usr/share/locale"
    ;;
  --docdir)
    echo "/usr/share/doc/postgresql"
    ;;
  --mandir)
    echo "/usr/share/man"
    ;;
esac
