#!/bin/sh

cd src
# ctest result lines look like: "1/3 Test #1: jsoncpp_test .....   Passed    0.01 sec"
# anything other than Passed/Skipped/Disabled (Failed, Timeout, Exception, Not Run) is a FAIL
ctest --force-new-ctest-process | awk '/Test +#[0-9]+:/ {
    if ($0 ~ /Passed/) res = "PASS"
    else if ($0 ~ /Skipped|Disabled/) res = "SKIP"
    else res = "FAIL"
    print res ": " $4; fflush()
}'
