SUMMARY = "This module provides the ConfigParser class which implements a basic configuration language which provides a structure similar to what's found in Microsoft Windows INI files."
SECTION = "devel/python"
HOMEPAGE = "https://docs.python.org/3/library/configparser.html"
LICENSE = "unknown"

LIC_FILES_CHKSUM = "file://PKG-INFO;beginline=10;endline=10;md5=23f9ad5cad3d8cc0336e2a5d8a87e1fa"

SRC_URI[md5sum] = "aaa80b58b6b0810e54f66486860b3ed1"
SRC_URI[sha256sum] = "da60d0014fd8c55eb48c1c5354352e363e2d30bbf7057e5e171a468390184c75"

inherit pypi
