SUMMARY = "comprehensive password hashing framework supporting over 30 schemes"
DESCRIPTION = "\
Passlib is a password hashing library for Python 2 & 3, which provides cross-platform \
implementations of over 30 password hashing algorithms, as well as a framework for \
managing existing password hashes. It’s designed to be useful for a wide range of \
tasks, from verifying a hash found in /etc/shadow, to providing full-strength password \
hashing for multi-user applications."
HOMEPAGE = "https://bitbucket.org/ecollins/passlib"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://LICENSE;md5=7ed8269648e55f7d37532503de04d3fe"

SRC_URI[md5sum] = "3c3c5733f2ada427060c33b5ece0560f"
SRC_URI[sha256sum] = "0be4f6053357c4ebba5578a065fbdad75a844501d4c6d91d4a3a0c1594c6abed"
