SUMMARY = "Pyiface is a package that exposes the network interfaces of the operating system in a easy to use and transparent way"
SECTION = "devel/python"
HOMEPAGE = "https://pypi.python.org/pypi/pyiface/"
LICENSE = "GPLv3+"

LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=4fe869ee987a340198fb0d54c55c47f1"

SRC_URI[md5sum] = "1bbc53c281925eae5f508b8b1a1f8259"
SRC_URI[sha256sum] = "83a64f5672cda48776ca9ed228dbf2e2df7b074a7dcb52ed4f6987322051928d"

inherit pypi
