SUMMARY = "Pyiface is a package that exposes the network interfaces of the operating system in a easy to use and transparent way"
SECTION = "devel/python"
HOMEPAGE = "https://pypi.python.org/pypi/pyiface/"
LICENSE = "GPLv3+"

LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=fe06497acaf4f45999925d348c2605f9"

SRC_URI[md5sum] = "edcdd71109c4259af8348006a8049c9c"
SRC_URI[sha256sum] = "dc984de0e1bcf6871ef88b1a92d1fb75717d4f602a60caeb66136093d4a8f62e"

inherit pypi
