SUMMARY = "Internationalised Domain Names in Applications"
HOMEPAGE = "https://github.com/kjd/idna"
LICENSE = "BSD-3-Clause & Python-2.0 & Unicode"
LIC_FILES_CHKSUM = "file://LICENSE.rst;md5=134bdad79491c37bdae32811572b4bc6"

SRC_URI[md5sum] = "e2d3f8a45d3d048a653eb186896e9e3e"
SRC_URI[sha256sum] = "0ac27740937d86850010e035c6a10a564158a5accddf1aa24df89b0309252426"

BBCLASSEXTEND = "native nativesdk"
