SUMMARY = "Fast, pure-Python full text indexing, search, and spell checking library."
DESCRIPTION = "\
Whoosh is a fast, featureful full-text indexing and searching library \
implemented in pure Python. Programmers can use it to easily add search \
functionality to their applications and websites. Every part of how \
Whoosh works can be extended or replaced to meet your needs exactly."
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=05303186defc6141143629961c7c8a60"

SRC_URI[md5sum] = "891edeba96cec53604c0cd176284c4cf"
SRC_URI[sha256sum] = "aa6db447522e208ae652c6ce063bb23cedec47f5ed630121b3debaa011fcb9c4"

PYPI_PACKAGE = "Whoosh"
PYPI_PACKAGE_EXT = "zip"
