#! /bin/sh
#
# This is an init script for openembedded
# Copy it to /etc/init.d/openldap and type
# > update-rc.d openldap defaults 60
#


slapd=/usr/libexec/slapd
test -x "$slapd" || exit 0


case "$1" in
  start)
    echo -n "Starting OpenLDAP: "
    start-stop-daemon --start --quiet --exec $slapd
    echo "."
    ;;
  stop)
    echo -n "Stopping OpenLDAP: "
    start-stop-daemon --stop --quiet --pidfile /var/run/slapd.pid
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/openldap {start|stop}"
    exit 1
esac

exit 0
