#!/bin/sh

trap "[ -d ~/.ssh.bak ] && rm -rf ~/.ssh && mv ~/.ssh.bak ~/.ssh || rm -rf ~/.ssh" INT EXIT
if [ -d ~/.ssh ]; then
  mv ~/.ssh ~/ssh.bak
fi

mkdir ~/.ssh
echo "Host localhost" >> ~/.ssh/config
echo "    StrictHostKeyChecking no" >> ~/.ssh/config

pytest -o log_cli=true -o log_cli_level=INFO | sed -e 's/\[...%\]//g'| sed -e 's/PASSED/PASS/g'| sed -e 's/FAILED/FAIL/g'|sed -e 's/SKIPPED/SKIP/g'| awk '{if ($NF=="PASS" || $NF=="FAIL" || $NF=="SKIP" || $NF=="XFAIL" || $NF=="XPASS"){printf "%s: %s\n", $NF, $0}else{print}}'| awk '{if ($NF=="PASS" || $NF=="FAIL" || $NF=="SKIP" || $NF=="XFAIL" || $NF=="XPASS") {$NF="";print $0}else{print}}'
