DESCRIPTION = "Machine specific systemd units"

LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COREBASE}/LICENSE;md5=3f40d7994397109285ec7b81fdeb3b58"

PACKAGE_ARCH = "${MACHINE_ARCH}"

PR = "r1"

inherit systemd
SYSTEMD_SERVICE_${PN} = ""
NATIVE_SYSTEMD_SUPPORT = "1"
ALLOW_EMPTY_${PN} = "1"
