GCC-4_6-BRANCH-LINARO-BACKPORTS = "        \
file://linaro/gcc-4.6-linaro-r106720.patch \
file://linaro/gcc-4.6-linaro-r106723.patch \
file://linaro/gcc-4.6-linaro-r106729.patch \
file://linaro/gcc-4.6-linaro-r106733.patch \
file://linaro/gcc-4.6-linaro-r106737.patch \
file://linaro/gcc-4.6-linaro-r106738.patch \
file://linaro/gcc-4.6-linaro-r106739.patch \
file://linaro/gcc-4.6-linaro-r106740.patch \
file://linaro/gcc-4.6-linaro-r106741.patch \
file://linaro/gcc-4.6-linaro-r106742.patch \
file://linaro/gcc-4.6-linaro-r106743.patch \
file://linaro/gcc-4.6-linaro-r106744.patch \
file://linaro/gcc-4.6-linaro-r106746.patch \
file://linaro/gcc-4.6-linaro-r106747.patch \
file://linaro/gcc-4.6-linaro-r106750.patch \
file://linaro/gcc-4.6-linaro-r106751.patch \
file://linaro/gcc-4.6-linaro-r106753.patch \
file://linaro/gcc-4.6-linaro-r106754.patch \
file://linaro/gcc-4.6-linaro-r106755.patch \
"
