#! /bin/sh
#
# This is an init script for openembedded
# Copy it to /etc/init.d/syslog-ng and type
# > update-rc.d syslog-ng defaults 5
#


syslog_ng=/usr/sbin/syslog-ng
test -x "$syslog_ng" || exit 0

case "$1" in
  start)
    echo -n "Starting syslog-ng:"
    start-stop-daemon --start --quiet --exec $syslog_ng
    echo "."
    ;;
  stop)
    echo -n "Stopping syslog-ng:"
    start-stop-daemon --stop --quiet --pidfile /var/run/syslog-ng.pid
    echo "."
    ;;
  reload|force-reload)
    start-stop-daemon --stop --quiet --signal 1 --exec $syslog_ng
    ;;
  restart)
    echo "Stopping syslog-ng:"
    start-stop-daemon --stop --quiet --pidfile /var/run/syslog-ng.pid
    echo -n "Waiting for syslog-ng to die off"
    for i in 1 2 3 ;
    do
        sleep 1
        echo -n "."
    done
    echo ""
    echo -n "Starting syslog-ng:"
    start-stop-daemon --start --quiet --exec $syslog_ng
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/syslog-ng {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
